name: Run tests 
#Run this workflow when we dev or main changes 
#because of a push or is about the changed by pull request
on:
  push:
    branches: [dev,main]
  pull_request: [dev, main]  

jobs:
  api-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test <--npm test is usually for unit test 
    - run: npm install -g pm2 
    # starting up server with node index disable to other terminal cmd
    - run: pm2 start index.js     
    - run: npm install -g newman
    - run: newman run test-rest-api/test.postman_collection.json
    